name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jar-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Save target
      uses: actions/upload-artifact@v2
      with:
        name: target-files
        path: target/*
        retention-days: 1

  docker-push:
    needs: jar-build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download target
      uses: actions/download-artifact@v2
      with:
        name: target-files
        path: target

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag economigos/economigos-app:latest

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: economigos
        password: grupo1adsa
        repository: economigos/economigos-app:latest
        tag_with_ref: true

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: economigos
        password: grupo1adsa
        registry: docker.pkg.github.com
        repository: economigos/economigos-app:latest
        tag_with_ref: true